import { ColumnOption, RenderType, ViewType } from "@/types";

export const COLUMNS_BY_VIEW: Record<string, ColumnOption[]> = {
    listens: [
        { key: 'ts', label: 'Date & Heure', description: 'Date et heure de l\'écoute', sortable: true, defaultVisible: true },
        { key: 'title', label: 'Titre', description: 'Titre du morceau', sortable: true, defaultVisible: true },
        { key: 'artist', label: 'Artiste', description: 'Artiste principal', sortable: true, defaultVisible: true },
        { key: 'album', label: 'Album', description: 'Album du morceau', sortable: true, defaultVisible: true },
        { key: 'msPlayed', label: 'Durée', description: 'Temps d\'écoute en secondes', sortable: true, defaultVisible: true },
        { key: 'reasonEnd', label: 'Raison Fin', description: 'Pourquoi l\'écoute s\'est arrêtée', sortable: true, defaultVisible: true },
        { key: 'isValid', label: 'Valide', description: 'Si l\'écoute est considérée comme valide (>= 30s)', sortable: true, defaultVisible: true },
        // Colonnes supplémentaires (non visibles par défaut)
        { key: 'platform', label: 'Plateforme', description: 'Plateforme d\'écoute (Spotify, Deezer, etc.)', sortable: true, defaultVisible: false },
        { key: 'userName', label: 'Utilisateur', description: 'Nom de l\'utilisateur', sortable: true, defaultVisible: false },
        { key: 'trackDuration', label: 'Durée Totale', description: 'Durée totale du morceau', sortable: true, defaultVisible: false },
        { key: 'explicit', label: 'Explicite', description: 'Contenu explicite', sortable: true, defaultVisible: false },
        { key: 'trackPopularity', label: 'Popularité Track', description: 'Score de popularité du mo rceau', sortable: true, defaultVisible: false },
        { key: 'albumReleaseDate', label: 'Date Sortie Album', description: 'Date de sortie de l\'album', sortable: true, defaultVisible: false },
        { key: 'albumPopularity', label: 'Popularité Album', description: 'Score de popularité de l\'album', sortable: true, defaultVisible: false },
        { key: 'subGenre', label: 'Sous-genre', description: 'Sous-genre musical', sortable: true, defaultVisible: false },
        { key: 'genre', label: 'Genre', description: 'Genre musical principal', sortable: true, defaultVisible: false },
        { key: 'artistPopularity', label: 'Popularité Artiste', description: 'Score de popularité de l\'artiste', sortable: true, defaultVisible: false },
        { key: 'country', label: 'Pays', description: 'Pays d\'origine de l\'artiste', sortable: true, defaultVisible: false },
        { key: 'region', label: 'Région', description: 'Région géographique', sortable: true, defaultVisible: false },
        { key: 'allArtists', label: 'Tous les Artistes', description: 'Liste de tous les artistes du morceau', sortable: true, defaultVisible: false },
        { key: 'allTags', label: 'Tags', description: 'Tags associés', sortable: true, defaultVisible: false },
    ],
    tracks: [
        { key: 'rank_num', label: 'Rang', description: 'Classement basé sur le nombre d\'écoutes', sortable: true, defaultVisible: true },
        { key: 'track_title', label: 'Titre', description: 'Titre du morceau', sortable: true, defaultVisible: true },
        { key: 'album_title', label: 'Album', description: 'Album du morceau', sortable: true, defaultVisible: true },
        { key: 'all_artists', label: 'Artistes', description: 'Tous les artistes participants', sortable: true, defaultVisible: true },
        { key: 'genre_name', label: 'Genre', description: 'Genre musical principal', sortable: true, defaultVisible: true },
        { key: 'valid_listens', label: 'Écoutes Valides', description: 'Nombre d\'écoutes supérieures à 30s', sortable: true, defaultVisible: true },
        { key: 'invalid_listens', label: 'Écoutes Invalides', description: 'Nombre d\'écoutes inférieures à 30s', sortable: true, defaultVisible: true },
        // Colonnes supplémentaires (non visibles par défaut)
        { key: 'sub_genre_name', label: 'Sous-genre', description: 'Sous-genre musical', sortable: true, defaultVisible: false },
        { key: 'all_tags', label: 'Tags', description: 'Tags associés au morceau', sortable: true, defaultVisible: false },
    ],
    artists: [
        { key: 'rank_num', label: 'Rang', description: 'Classement de l\'artiste', sortable: true, defaultVisible: true },
        { key: 'artist_name', label: 'Artiste', description: 'Nom de l\'artiste', sortable: true, defaultVisible: true },
        { key: 'country_name', label: 'Pays', description: 'Pays d\'origine de l\'artiste', sortable: true, defaultVisible: true },
        { key: 'genre_name', label: 'Genre', description: 'Genre principal de l\'artiste', sortable: true, defaultVisible: true },
        { key: 'valid_listens', label: 'Écoutes Valides', description: 'Total des écoutes valides pour cet artiste', sortable: true, defaultVisible: true },
        { key: 'invalid_listens', label: 'Écoutes Invalides', description: 'Total des écoutes invalides pour cet artiste', sortable: true, defaultVisible: true },
        // Colonnes supplémentaires (non visibles par défaut)
        { key: 'sub_genres', label: 'Sous-genres', description: 'Liste des sous-genres de l\'artiste', sortable: true, defaultVisible: false },
    ],
    albums: [
        { key: 'rank_num', label: 'Rang', description: 'Classement de l\'album', sortable: true, defaultVisible: true },
        { key: 'album_title', label: 'Album', description: 'Titre de l\'album', sortable: true, defaultVisible: true },
        { key: 'release_date', label: 'Date de Sortie', description: 'Date de sortie de l\'album', sortable: true, defaultVisible: true },
        { key: 'all_artists', label: 'Artistes', description: 'Artistes de l\'album', sortable: true, defaultVisible: true },
        { key: 'valid_listens', label: 'Écoutes Valides', description: 'Total des écoutes valides pour cet album', sortable: true, defaultVisible: true },
        { key: 'invalid_listens', label: 'Écoutes Invalides', description: 'Total des écoutes invalides pour cet album', sortable: true, defaultVisible: true },
    ],
}

// Configuration: mapping des clés de colonnes vers les noms de champs dans les données
export const COLUMN_FIELD_MAPPINGS: Record<ViewType, Record<string, string>> = {
    listens: {
        ts: 'listen_timestamp',
        title: 'track_title',
        artist: 'primary_artist_name',
        album: 'album_title',
        msPlayed: 'ms_played',
        reasonEnd: 'reason_end',
        isValid: 'is_valid',
        platform: 'platform',
        userName: 'user_name',
        trackDuration: 'duration_ms',
        explicit: 'explicit',
        trackPopularity: 'track_popularity',
        albumReleaseDate: 'album_release_date',
        albumPopularity: 'album_popularity',
        subGenre: 'sub_genre_name',
        genre: 'genre_name',
        artistPopularity: 'primary_artist_popularity',
        country: 'country_name',
        region: 'region_name',
        allArtists: 'all_artists',
        allTags: 'all_tags',
    },
    tracks: {
        rank_num: 'rank_num',
        track_title: 'track_title',
        album_title: 'album_title',
        all_artists: 'all_artists',
        genre_name: 'genre_name',
        valid_listens: 'valid_listens',
        invalid_listens: 'invalid_listens',
        sub_genre_name: 'sub_genre_name',
        all_tags: 'all_tags',
    },
    artists: {
        rank_num: 'rank_num',
        artist_name: 'artist_name',
        country_name: 'country_name',
        genre_name: 'genre_name',
        valid_listens: 'valid_listens',
        invalid_listens: 'invalid_listens',
        sub_genres: 'sub_genres',
    },
    albums: {
        rank_num: 'rank_num',
        album_title: 'album_title',
        release_date: 'release_date',
        all_artists: 'all_artists',
        valid_listens: 'valid_listens',
        invalid_listens: 'invalid_listens',
    }
}

export const COLUMN_RENDER_TYPES: Record<string, RenderType> = {
    // Listens
    ts: 'timestamp',
    title: 'title',
    artist: 'text',
    album: 'text',
    msPlayed: 'duration',
    reasonEnd: 'text',
    isValid: 'boolean',
    platform: 'text',
    userName: 'text',
    trackDuration: 'duration',
    explicit: 'boolean',
    trackPopularity: 'number',
    albumReleaseDate: 'date',
    albumPopularity: 'number',
    subGenre: 'badge',
    genre: 'badge',
    artistPopularity: 'number',
    country: 'text',
    region: 'text',
    allArtists: 'text',
    allTags: 'text',

    // Tracks, Artists, Albums communs
    rank_num: 'rank',
    track_title: 'title',
    album_title: 'text',
    artist_name: 'title',
    all_artists: 'text',
    country_name: 'text',
    genre_name: 'badge',
    release_date: 'date',
    valid_listens: 'validListens',
    invalid_listens: 'invalidListens',
    sub_genre_name: 'badge',
    all_tags: 'text',
    sub_genres: 'text',
}

// Configuration: styles CSS pour chaque type de rendu
export const COLUMN_CELL_STYLES: Record<RenderType, string> = {
    timestamp: 'font-medium text-muted-foreground',
    date: 'text-muted-foreground',
    title: 'font-semibold text-foreground',
    text: '',
    rank: 'font-bold text-muted-foreground w-16 text-center',
    duration: 'text-right tabular-nums',
    badge: '',
    boolean: '',
    number: 'text-right tabular-nums',
    validListens: 'text-right font-medium text-green-600 dark:text-green-400 tabular-nums',
    invalidListens: 'text-right text-muted-foreground tabular-nums'
}