-- REMPLISSAGE DES TABLES DE REFERENCE (geographical_regions et countries)
-- Ce script insere les donnees de reference.

-- Insertion des regions geographiques uniques
INSERT INTO geographical_regions (name) VALUES
('Asie du Sud'),
('Afrique Australe'),
('Balkans'),
('Maghreb'),
('Europe de l Ouest'),
('Afrique Centrale'),
('Amerique Latine'),
('Moyen-Orient'),
('Oceanie'),
('Europe de l Est'),
('Afrique de l Ouest'),
('Afrique de l Est'),
('Asie du Sud-Est'),
('Amerique du Nord'),
('Asie de l Est'),
('Asie Centrale')
ON CONFLICT (name) DO NOTHING;

-- Insertion des pays et liaison avec les regions geographiques
INSERT INTO countries (name, region_id) VALUES
('Afghanistan', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Afrique du Sud', (SELECT id FROM geographical_regions WHERE name = 'Afrique Australe')),
('Albanie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Algerie', (SELECT id FROM geographical_regions WHERE name = 'Maghreb')),
('Allemagne', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Andorre', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Angola', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Antigua-et-Barbuda', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Arabie saoudite', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Argentine', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Armenie', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Australie', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Autriche', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Azerbaidjan', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Bahamas', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Bahrein', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Bangladesh', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Barbade', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Belgique', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Belize', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Benin', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Bhoutan', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Bielorussie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Birmanie Myanmar', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Bolivie', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Bosnie-Herzegovine', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Botswana', (SELECT id FROM geographical_regions WHERE name = 'Afrique Australe')),
('Bresil', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Brunei', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Bulgarie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Burkina Faso', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Burundi', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Cambodge', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Cameroun', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Canada', (SELECT id FROM geographical_regions WHERE name = 'Amerique du Nord')),
('Cap-Vert', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Centrafrique', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Chili', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Chine', (SELECT id FROM geographical_regions WHERE name = 'Asie de l Est')),
('Chypre', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Colombie', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Comores', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Congo', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Congo Republique democratique', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Coree du Nord', (SELECT id FROM geographical_regions WHERE name = 'Asie de l Est')),
('Coree du Sud', (SELECT id FROM geographical_regions WHERE name = 'Asie de l Est')),
('Costa Rica', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Cote d Ivoire', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Croatie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Cuba', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Danemark', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Djibouti', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Dominique', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Egypte', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Emirats arabes unis', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Equateur', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Erythree', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Espagne', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Estonie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Eswatini', (SELECT id FROM geographical_regions WHERE name = 'Afrique Australe')),
('Etats-Unis', (SELECT id FROM geographical_regions WHERE name = 'Amerique du Nord')),
('Ethiopie', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Fidji', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Finlande', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('France', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Gabon', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Gambie', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Georgie', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Ghana', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Grece', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Grenade', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Guatemala', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Guinee', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Guinee equatoriale', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Guinee-Bissau', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Guyana', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Haiti', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Honduras', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Hongrie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Iles Marshall', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Iles Salomon', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Inde', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Indonesie', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Irak', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Iran', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Irlande', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Islande', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Israel', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Italie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Jamaique', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Japon', (SELECT id FROM geographical_regions WHERE name = 'Asie de l Est')),
('Jordanie', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Kazakhstan', (SELECT id FROM geographical_regions WHERE name = 'Asie Centrale')),
('Kenya', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Kirghizistan', (SELECT id FROM geographical_regions WHERE name = 'Asie Centrale')),
('Kiribati', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Koweit', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Laos', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Lesotho', (SELECT id FROM geographical_regions WHERE name = 'Afrique Australe')),
('Lettonie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Liban', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Liberia', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Libye', (SELECT id FROM geographical_regions WHERE name = 'Maghreb')),
('Liechtenstein', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Lituanie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Luxembourg', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Macedoine du Nord', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Madagascar', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Malaisie', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Malawi', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Maldives', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Mali', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Malte', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Maroc', (SELECT id FROM geographical_regions WHERE name = 'Maghreb')),
('Maurice', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Mauritanie', (SELECT id FROM geographical_regions WHERE name = 'Maghreb')),
('Mexique', (SELECT id FROM geographical_regions WHERE name = 'Amerique du Nord')),
('Micronesie', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Moldavie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Monaco', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Mongolie', (SELECT id FROM geographical_regions WHERE name = 'Asie de l Est')),
('Montenegro', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Mozambique', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Namibie', (SELECT id FROM geographical_regions WHERE name = 'Afrique Australe')),
('Nauru', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Nepal', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Nicaragua', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Niger', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Nigeria', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Norvege', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Nouvelle-Zelande', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Oman', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Ouganda', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Ouzbekistan', (SELECT id FROM geographical_regions WHERE name = 'Asie Centrale')),
('Pakistan', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Palaos', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Panama', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Papouasie-Nouvelle-Guinee', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Paraguay', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Pays-Bas', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Perou', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Philippines', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Pologne', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Portugal', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Qatar', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Roumanie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Royaume-Uni', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Russie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Rwanda', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Saint-Christophe-et-Nieves', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Saint-Marin', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Saint-Vincent-et-les-Grenadines', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Sainte-Lucie', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Salvador', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Samoa', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Sao Tome-et-Principe', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Senegal', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Serbie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Seychelles', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Sierra Leone', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Singapour', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Slovaquie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Slovenie', (SELECT id FROM geographical_regions WHERE name = 'Balkans')),
('Somalie', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Soudan', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Soudan du Sud', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Sri Lanka', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud')),
('Suede', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Suisse', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Suriname', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Syrie', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Tadjikistan', (SELECT id FROM geographical_regions WHERE name = 'Asie Centrale')),
('Tanzanie', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Tchad', (SELECT id FROM geographical_regions WHERE name = 'Afrique Centrale')),
('Tchequie', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Thailande', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Timor oriental', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Togo', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Ouest')),
('Tonga', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Trinite-et-Tobago', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Tunisie', (SELECT id FROM geographical_regions WHERE name = 'Maghreb')),
('Turkmenistan', (SELECT id FROM geographical_regions WHERE name = 'Asie Centrale')),
('Turquie', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Tuvalu', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Ukraine', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Est')),
('Uruguay', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Vanuatu', (SELECT id FROM geographical_regions WHERE name = 'Oceanie')),
('Vatican', (SELECT id FROM geographical_regions WHERE name = 'Europe de l Ouest')),
('Venezuela', (SELECT id FROM geographical_regions WHERE name = 'Amerique Latine')),
('Vietnam', (SELECT id FROM geographical_regions WHERE name = 'Asie du Sud-Est')),
('Yemen', (SELECT id FROM geographical_regions WHERE name = 'Moyen-Orient')),
('Zambie', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est')),
('Zimbabwe', (SELECT id FROM geographical_regions WHERE name = 'Afrique de l Est'))
ON CONFLICT (name) DO NOTHING;

-- Message de succes
SELECT 'Tables de reference remplies avec succes!' as message;
